### ISSUE TITLE
Possible problem in CAttribute -> isLeaf()

### ISSUE THREAD

**Issue by BertVerhees** [openEHR/archie#241]
I think it is just doing the oppositie thing one expects.

Anyway, I don't see how an attribute can be a leaf, but if the method is there it should work as expected.

Or do I misunderstand the concept of CAttribute?

Thanks for any comment.

**Comment by pieterbos** [comment]
Good catch, that is indeed a problem. 

The specification says about this method:

True if this node is a terminal node in the tree structure, i.e. having no child nodes.

So it should be there, just implemented correctly. And a c_attribute can be a leaf node in the sense that it can be without children. That mainly seems useful to know during modeling, when one has added an attribute, but not yet any children.

I’ll fix it soon.
