### ISSUE TITLE
JSON deserialization of operands of Operator broken

### ISSUE THREAD

**Issue by J3173** [openEHR/archie#269]
When serializing and then deserializing a BinaryOperator, ForAllStatement or UnaryOperator using `JacksonUtil.getObjectMapper().writeValueAsString` and `.readValue`, the `operands` list is not filled.

**Comment by pieterbos** [comment]
That is because of the following code:

```
   @JsonIgnore //the subclasses have the right methods for operands
    public List<Expression> getOperands() {
        return operands;
    }
```

meaning you should probably use leftOperand and rightOperand here, or in case of UnaryOperator, just operand.

Do you still consider this an issue?

**Comment by pieterbos** [comment]
I should probably remove the leftOperand and rightOperand for UnaryOperator though I guess?

**Comment by J3173** [comment]
> meaning you should probably use leftOperand and rightOperand here, or in case of UnaryOperator, just operand.

Then we should add setters for leftOperand/rightOperand/operand in those classes, so Jackson can fill them?

**Comment by pieterbos** [comment]
Agreed, we should. Or we should move everything to 'operands', for all operators, and migrate all code that uses this to that. also very doable.

**Comment by pieterbos** [comment]
This has been fixed in master, so closing this.
