### ISSUE TITLE
Intellij Idea gradle problem: cannot create directory

### ISSUE THREAD

**Issue by serefarikan** [openEHR/archie#315]
Trying to open the archie folder with a reasonably recent version of Intellij Idea (Ultimate, 2020.3) , I get the following error: 

`Could not create parent directory for lock file /work/data/.gradle/wrapper/dists/gradle-6.5.1-bin/1m5048aptkfynhbvolwgr4ej9/gradle-6.5.1-bin.zip.lck`

This is my ubuntu 20.04 development machine. 
`java --version` 
gives:
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

I've been looking for a solution but the suggestions I found are not applicable to my version of Idea. 

Is this a known issue? If so, it would be good to document it in the main README. I'll make a pull req if I find a good solution, but just in case someone came across this...

**Comment by serefarikan** [comment]
as the error indicates, intellij is somehow attempting to access the root folder of my linux machine, which won't be allowed of course. I have no idea why gradle settings of the IDE are defaulting to this. closing this issue, but in case someone finds this via google, they may check idea's gradle settings is not pointing at a location it cannot write to.

**Comment by pieterbos** [comment]
Interesting. I use Intellij myself to develop Archie, on MacOS, and I do not have this issue. I also know of people who have opened this in IntelliJ on windows without problems - I'm guessing some of the people here at Nedap have also tried Linux, but I would have to ask people.
I assume you managed to fixed the problem?

**Comment by serefarikan** [comment]
@pieterbos  thanks. yes, I just changed the folder it was trying to use to something under my home folder, which solved the problem. 
I thought you'd be using idea and given archie is using gradle, I thought you must be happy with it. thanks again.
