### ISSUE TITLE
Additional information requested in archetype validation result messages

### ISSUE THREAD

**Issue by cnanjo** [openEHR/archie#33]
I loaded in an InMemoryFullArchetypeRepository three archetypes: A, B, C where C specializes B which specializes A (meaning A is the root of the dependency hierarchy). In Archetype B, I define a value set ac0.2 in the terminology and term-binding sections of the archetype definition. Yet, that value set is never used in the archetype definition. 

terminology
	term_definitions = <
		["en"] = <
			...
			["ac0.2"] = <
				text = <"Finding statement topic code range value set">
				description = <"Range for the associated finding SWEC attribute restricted to findings and observable entities subhierarchy">
			>
		>
	>

	term_bindings = <
    	["snomed-ct"] = <
		        ...
		        ["ac0.2"] = <http://example.com/valuesets/finding_statement_topic_result_range_vs.v0.0.1>
	    >
	>

This leads to the following two errors:

Error: parent archetype not found or can not be flattened - archetype specialisation parent identifier validity. The archetype identifier stated in the specialise clause must be the identifier of the immediate specialisation parent archetype.
Warning: ac0.2 - codein terminology not used in archetype definition

Note that: (1) neither error above specifies which archetype is affected. I would suggest adding this information since it is very helpful for debugging. I fixed another set of errors in my archetypes but had to hunt for them since I was not informed by the result messages where the error was happening. (2) The second error results because the warning in archetype B prevents it from being flattened (flattening is skipped if messages.size() > 0 even if the message is a warning rather than an error) and thus flattened=null for the parent of archetype C preventing the flattening of archetype C itself. It might be helpful to support a strict mode and a relaxed mode where warnings don't stop the flattening process.

**Comment by pieterbos** [comment]
Hello Claude:

1: You can just get all the ValidationResults from the archetype repository. Each contains both the archetype, the flattened archetype, all error messages and all error messages of all template overlays. So you should be able to get the archetype id with the messages easily.
2. If you still want to flatten a failed archetype you can use the Flattener class yourself and still flatten the archetype. A relaxed mode could be a nice added feature, but you can certainly do without it. Feel free to create a pull request for that.

**Comment by pieterbos** [comment]
Oh, i see the problem with point 2, it should ignore warnings in whether it can try to flatten.

**Comment by pieterbos** [comment]
Since 2 has been fixed, I think this issue can be closed.

**Comment by pieterbos** [comment]
In https://github.com/openEHR/archie/pull/31 I added an option to always try to flatten, regardless of errors. This is only useful for modelling purposes - the archetype will be invalid and must be fixed before it is used any further.
