### ISSUE TITLE
Suggestion to rename isSpecialized() method in Archetype.java

### ISSUE THREAD

**Issue by cnanjo** [openEHR/archie#34]
Type: API enhancement request
Importance: low

The Archetype.isSpecialized() method is defined as follows:

    public boolean isSpecialized() {
        return this.parentArchetypeId != null;
    }

The name is confusing because, in this case, the archetype in question 'specializes' the parent and the parent is specialized by the archetype in question.

Suggest renaming isSpecialized() to specializes().

**Comment by pieterbos** [comment]
The isSpecialized method is defined in the AOM 2 spec at http://openehr.org/releases/AM/latest/docs/AOM2/AOM2.html#_archetype_class, and archie just implements the standard method. If you want it changed, I think you should file a change request there.
