### ISSUE TITLE
DvDate.getMagnitude returns incorrect value

### ISSUE THREAD

**Issue by J3173** [openEHR/archie#349]
According to the [specification](https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_date_class) the `magnitude` of the date `0001-01-01` should be 0, but `new DvDate(LocalDate.of(1, 1, 1)).getMagnitude()` return -719162.

**Comment by pieterbos** [comment]
Fixed in #347 
However, I have not changed the return type for DV_DATE_TIME.getMagnitude to Double, it is still long. Making it double will make it support fractional seconds, but also will be less accurate and will require more work. Should I?

**Comment by pieterbos** [comment]
Oh, accuracy should probably ok, current date is around 11 digits, which leaves some room in double precision to add a couple of fractions...

**Comment by pieterbos** [comment]
Closing this, has been solved and merged.
