### ISSUE TITLE
[Question] Missing fixes in release 1.0.4

### ISSUE THREAD

**Issue by subigre** [openEHR/archie#368]
Hi @pieterbos, I am wondering if there is a reason why the release `1.0.4`  does not include all changes performed during the past few weeks? 
I am asking because I just encountered this [issue](https://github.com/openEHR/archie/pull/350) with EHRbase and I see that the PR was closed on 15 Sept.

**Comment by pieterbos** [comment]
My apologies, we were in a hurry to get one issue fixed. We will create a 1.0.5 soon that will include all fixes in the main branch. It will not include some new functionality that will add some breaking changes that is also in the master branch, that will come in a later release, likely within a couple of weeks.

**Comment by subigre** [comment]
Thanks for the fast reply
