### ISSUE TITLE
adl parsing

### ISSUE THREAD

**Issue by orionkishan** [openEHR/archie#473]
Hi, I am trying to parse the adl file using Archie and convert it to JSON, but, parser.parse(name_of_the_adl_file) is giving me mismatched input 'name_of_the_adl_file' expecting {SYM_ARCHETYPE, SYM_TEMPLATE, SYM_OPERATIONAL_TEMPLATE, SYM_TEMPLATE_OVERLAY} error. 
I have tried with blood pressure adl and adl2 from CKM
Please help

**Comment by pieterbos** [comment]
The ADL parser does not have a method to which you can pass a filename as an argument. You will have to open the file yourself. Then either pass the content of the ADL file as a String, not the file name, or an InputStream providing the content of the ADL file.
