### ISSUE TITLE
Unable to remove a BmmGenericParameter from BmmGenericClass

### ISSUE THREAD

**Issue by cnanjo** [openEHR/archie#55]
At this time, one cannot remove a parameter from a BmmGenericClass. Doing BmmGenericClass.getGenericParameters() returns a copy of the collection so removing the parameter from the collection is not reflected in the class. I recommend adding a method called removeGenericParameter(BmmGenericParameter) to BmmGenericClass and perhaps removeGenericParameter(String paramName).

**Comment by pieterbos** [comment]
I merged the pull request you created, so I think I can safely close this issue.
