### ISSUE TITLE
Parsing RM Object via JacksonUtil with Validation

### ISSUE THREAD

**Issue by jakesmolka** [openEHR/archie#89]
Thanks for Archie and the comprehensive documentation! But I found a behavior where I'm not sure if I miss a step or if it's unexpected.

Parsing a RM object via `JacksonUtil` allows the creation of instances that do not comply to the RM. For instance, parsing a JSON of an `ItemStructure` without `name` or `archetype_node_id` will work, but they are required by RM. Is that expected? If yes, is there a way to validate RM objects against the RM without archetypes?

For transparency, this is what I tried:
``` java
String input = "{\n" +
                "    \"@type\": \"ITEM_LIST\",\n" +
                //"    \"archetype_node_id\": \"at0001\",\n" +
                "    \"name\": {\n" +
                "        \"@type\": \"DV_TEXT\",\n" +
                "        \"value\": \"test\"\n" +
                "    },\n" +
                "    \"items\": []\n" +
                "}";
ItemStructure test;
try {
        test = JacksonUtil.getObjectMapper().readValue(input, ItemStructure.class);
} catch (Exception e) {
        return e.getMessage();
}
```

**Comment by pieterbos** [comment]
Archie has Object instance creation and validation decoupled, both for the RM and for archetypes. This has quite a lot of benefits. So yes, this behaviour is expected.

The RMObjectValidator can validate against an archetype - specifically against an OperationalTemplate. It also validates many of the RM constraints, such as mandatory attributes, but it is not complete.

There is currently no way to validate RM Objects without archetypes. However, that should be easy to write based on the current RMObjectValidator - at least the basics such as mandatory fields. It could take a while before it becomes a priority for us. If you're in a hurry, feel free to write it yourself and create a pull request.

**Comment by wolandscat** [comment]
You have available within the BMM structure for any class the information indicating all mandatory elements, so I would have thought you could RM-validate just against this, without reference to any archetype - or is this what you are saying above @pieterbos ?

**Comment by pieterbos** [comment]
Yes, all information is available to do this, both in the BMM and in the metadata from the annotated RM implementation. The RMObjectValidator uses the metadata from the annotated RM implementation plus an archetype to validate many constraints already.
Just an implementation to validate RM Objects based on the model information only, without an archetype, has not yet been built.

**Comment by pieterbos** [comment]
Since most of the code was present anyway, I made https://github.com/openEHR/archie/pull/90 . It contains only the most basic tests, and it tests mainly if all mandatory fields have been set. Even better would be a way to add some custom validations to specific RM types, to add the validations that require custom implementation.
@jakesmolka does that help, and if so, could you test it?

**Comment by jakesmolka** [comment]
That was fast, thanks! I'll test it now.

**Comment by jakesmolka** [comment]
Works in my test case, i.e. tells me that and what is missing to comply with the RM. Great!

Yet working with the validation's result is not clear for me. Does `RMObjectValidationMessage` always represent an error, so there's none if the validation was successful? It seems their semantics isn't described in the documentation, yet. Maybe an additional piece of information like below of https://github.com/openEHR/archie#validating-rm-objects-against-an-archetype would be handy. :)

**Comment by pieterbos** [comment]
It certainly would be a good idea to document this. Currently, such a Message is always an error. The documentation mentions this API is still unstable. A message level (info, warning, error) could be useful, or perhaps a rename to RmObjectValidationError. Feel free to write some documentation, or add some code improvements in a pull request ;)
